---

- name: start AMS Central Manager
  run_once: true
  uri:
     url: "https://marathon.service.consul:8443/v2/groups/amscm"
     user: "{{marathon_username}}"
     password: "{{marathon_password}}"
     validate_certs: "no"
     method: PUT
     HEADER_Content-Type: "application/json"
     body: "{{ lookup('template', 'templates/groups.json') }}"
     body_format: json
  register: result
  until: result.status == 200
  retries: 10
  delay: 20
  changed_when: false
  tags:
    - ams_apps
